### ISSUE TITLE
 Error: failed to load 'sap/ushell/library.js' from resources/sap/ushell/library.js

### ISSUE THREAD

**Issue by leonli0912** [ArnaudBuchholz/training-ui5con18-opa#2]
I clone the demo project and run it successfully. 
#### Reproduce
I did a little change to the manifest.json as below:
`	"sap.ui5": {
		"dependencies": {
			"libs": {
				"sap.ui.core": {
					"lazy": false
				},
				"sap.m": {
					"lazy": false
				},
				"sap.ui.layout": {
					"lazy": false
				},
				"sap.ui.unified": {
					"lazy": false
				},
				"sap.ushell": {
					"lazy": false
				}
			}
		},
`
add another lib 'sap.ushell'.
then run the opa again with: 'ui5 serve -o'
### Symptom
The opa cannot run, in the developers tool of chrome, i found the error:
Error: failed to load 'sap/ushell/library.js' from resources/sap/ushell/library.js: 404 - Not Found...
### Explaination
I did this change because when I trying to enable ui5 tooling to my existing projects, I can not run OPA successfully.
If i mannually add the lib by 'ui5 add <lib>', then more errors occurs, like 'File not found: /resources/sap/ui/core/themes/sap_belize/base.less'
...

**Comment by ArnaudBuchholz** [comment]
Sorry for the late answer, this project has been on pause for quite some time.
I just updated it because I will release v2 of `ui5-test-runner` and I use it to do some tests and I saw the incident.

I also tried it and got the same issue, I would recommend creating an incident to tooling queue : https://github.com/SAP/ui5-tooling/issues.

Yet, it is possible to run it if you don't use the @ui5/cli but rather link directly to UI5 through https://ui5.sap.com.
For instance, inside this project, use `npm run reserve` and modify the manifest, you'll see that it works fine.

I hope it helps, closing the incident.
